/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Revaldi
 */
public class formPKL extends javax.swing.JFrame {

    /**
     * Creates new form formPKL
     */
    private void kosongkanform(){
        txtNama2.setText(null);
        txtNIM2.setText(null);
        txtFakultas2.setText(null);
        txtJurusan2.setText(null);
        txtKota.setText(null);
        txtTempat.setText(null);
        txtSKS.setText(null);
    }
    
    private void input(String a,String b,String c,String d,String e,String f,String g){
        pengajuan_pkl form1 = new pengajuan_pkl();
        form1.setNama(a);
        form1.setNIM(b);
        form1.setJurusan(c);
        form1.setFakultas(d);
        form1.setKotaPKL(e);
        form1.setTempatPKL(f);
        form1.setTempatPKL(g);
        
        form1.printData();
    }
    public formPKL() {
        initComponents();
        kosongkanform();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNama2 = new javax.swing.JTextField();
        txtNIM2 = new javax.swing.JTextField();
        txtJurusan2 = new javax.swing.JTextField();
        txtFakultas2 = new javax.swing.JTextField();
        txtKota = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        txtSKS = new javax.swing.JTextField();
        simpanBtn_pkl = new javax.swing.JButton();
        printBtn_pkl = new javax.swing.JButton();
        kosongkanBtn_pkl = new javax.swing.JButton();
        jLabel1_pkl = new javax.swing.JLabel();
        jLabel2_pkl = new javax.swing.JLabel();
        jLabel3_pkl = new javax.swing.JLabel();
        jTxtField4_pkl = new javax.swing.JLabel();
        jLabel5_pkl = new javax.swing.JLabel();
        jLabel6_pkl = new javax.swing.JLabel();
        jLabel7_pkl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        simpanBtn_pkl.setText("Simpan");
        simpanBtn_pkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtn_pklActionPerformed(evt);
            }
        });

        printBtn_pkl.setText("Print");
        printBtn_pkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtn_pklActionPerformed(evt);
            }
        });

        kosongkanBtn_pkl.setText("Kosongkan");

        jLabel1_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_pkl.setText("Nama");

        jLabel2_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2_pkl.setText("NIM");

        jLabel3_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3_pkl.setText("Jurusan");

        jTxtField4_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jTxtField4_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTxtField4_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jTxtField4_pkl.setText("Fakultas");

        jLabel5_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5_pkl.setText("Kota Tujuan");

        jLabel6_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6_pkl.setText("Tempat ");

        jLabel7_pkl.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7_pkl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7_pkl.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7_pkl.setText("SKS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2_pkl)
                    .addComponent(jLabel1_pkl)
                    .addComponent(jLabel3_pkl)
                    .addComponent(jTxtField4_pkl)
                    .addComponent(jLabel5_pkl)
                    .addComponent(jLabel6_pkl)
                    .addComponent(jLabel7_pkl))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTempat)
                    .addComponent(txtSKS)
                    .addComponent(txtKota)
                    .addComponent(txtFakultas2)
                    .addComponent(txtNIM2)
                    .addComponent(txtJurusan2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(kosongkanBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNama2))
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1_pkl))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNIM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_pkl))
                        .addGap(28, 28, 28)
                        .addComponent(txtJurusan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3_pkl))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFakultas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtField4_pkl))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_pkl))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6_pkl))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7_pkl))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kosongkanBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanBtn_pkl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printBtn_pklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtn_pklActionPerformed
        String inputNama = txtNama2.getText();
        String inputNIM = txtNIM2.getText();
        String inputJurusan = txtFakultas2.getText();
        String inputFakultas = txtKota.getText();
        String inputKota = txtKota.getText();
        String inputTempat = txtTempat.getText();
        String inputSKS = txtSKS.getText();

        //output
        input(inputNama,inputNIM,inputJurusan,inputFakultas,inputKota,inputTempat,inputSKS);
    }//GEN-LAST:event_printBtn_pklActionPerformed

    private void simpanBtn_pklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtn_pklActionPerformed
        try{
            String sql = "INSERT INTO pkl VALUES ('"
            + txtNama2.getText()
            +"','"+txtNIM2.getText()
            +"','"+txtFakultas2.getText()
            +"','"+txtKota.getText()
            +"','"+txtKota.getText()
            +"','"+txtTempat.getText()
            +"','"+txtSKS.getText()+
            "')";
            java.sql.Connection conn = (Connection)konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses simpan data berhasil");

        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosongkanform();
    }//GEN-LAST:event_simpanBtn_pklActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPKL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPKL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPKL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPKL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPKL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_pkl;
    private javax.swing.JLabel jLabel2_pkl;
    private javax.swing.JLabel jLabel3_pkl;
    private javax.swing.JLabel jLabel5_pkl;
    private javax.swing.JLabel jLabel6_pkl;
    private javax.swing.JLabel jLabel7_pkl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTxtField4_pkl;
    private javax.swing.JButton kosongkanBtn_pkl;
    private javax.swing.JButton printBtn_pkl;
    private javax.swing.JButton simpanBtn_pkl;
    private javax.swing.JTextField txtFakultas2;
    private javax.swing.JTextField txtJurusan2;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNIM2;
    private javax.swing.JTextField txtNama2;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
